#!/bin/bash

source /ext3/env.sh
conda activate diffdock-pocket
cd /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/jeg10045_kinase_scripts/diffdock/DiffDock

python evaluate_alloset.py --config default_inference_args.yaml --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir data/allosteric_dataset/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./rng_sqrt_0.5_1_1_1-results --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2 --model_dir 'workdir/test_score/rng_sqrt_0.5_1_1_1' --cache_path data/__cache --temp_sampling_tor 1.0 --temp_sampling_tr 1.0 --temp_sampling_rot 1.0 --inference_steps 20 --ligand_file fixed_ligand

#python evaluate_alloset.py --config default_inference_args.yaml --model_dir workdir/cb_test --ckpt last_model.pt --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir /vast/eac709/allo_crossdock/dataset_241120/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./results --smile_file ../../preprocessed_ligs/smiles.txt --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2

#python evaluate_alloset.py --config default_inference_args.yaml --model_dir ./workdir/test_score/allo-only --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir /vast/eac709/allo_crossdock/dataset_241120/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./results --smile_file ../../preprocessed_ligs/smiles.txt --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2

#python evaluate_alloset.py --config default_inference_args.yaml --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir data/allosteric_dataset/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./weighted_tor_notemp_results --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2 --model_dir allo-weighted-tor --cache_path data/__cache --temp_sampling_tor 1.0 --temp_sampling_tr 1.0 --temp_sampling_rot 1.0 --inference_steps 20

#python evaluate_alloset.py --config default_inference_args.yaml --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir data/allosteric_dataset/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./weighted_tor_lin_fixed_notemp_results --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2 --model_dir weighted_tor_lin_fixed --cache_path data/__cache --temp_sampling_tor 1.0 --temp_sampling_tr 1.0 --temp_sampling_rot 1.0 --inference_steps 20

#python evaluate_alloset.py --config default_inference_args.yaml --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir data/allosteric_dataset/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./allo_only_final_splits_results --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2 --model_dir workdir/test_score/allo_only_final_splits --cache_path data/__cache --inference_steps 20


#python evaluate_alloset.py --config default_inference_args.yaml --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir data/allosteric_dataset/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./test_results2 --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2 --model_dir workdir/test_score/weighted_tor_heur_final_splits --cache_path data/__cache --temp_sampling_tor 1.0 --temp_sampling_tr 1.0 --temp_sampling_rot 1.0 --inference_steps 20 --ligand_file fixed_ligand


#python evaluate_alloset.py --config default_inference_args.yaml --split_path /vast/eac709/allo_crossdock/splits/all_241120.txt --batch_size 10 --data_dir /vast/eac709/allo_crossdock/dataset_241120/ --tqdm --chain_cutoff 10 --dataset alloset --protein_file protein --out_dir ./results --smile_file ../../preprocessed_ligs/smiles.txt --esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --slurm_array_idx $1 --slurm_array_task_count $2 --model_dir weighted_tor_lin_fixed --cache_path data/__cache --temp_sampling_tor 1.0 --temp_sampling_tr 1.0 --temp_sampling_rot 1.0 --inference_steps 20
