#!/bin/bash

source /ext3/env.sh
conda activate diffdock-pocket
cd /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/jeg10045_kinase_scripts/diffdock/DiffDock
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes --split_train /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes/complex_names.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name allo-supersample
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --pdbbind_dir data/allosteric_dataset/ --split_train allo_train_split.txt --split_val allo_test_split.txt --val_inference_freq 1 --train_inference_freq 1 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name allo-only
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path data/esm_embedding_output --n_epochs 100 --pin_memory --DDP 
#python -m cProfile -s cumtime train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path data/esm_embedding_output --n_epochs 1 --pin_memory --DDP --limit_complexes 100
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes --split_train /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes/complex_names.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name allo-supersample --limit_complexes 10
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/super_snp_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes --split_train /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/supersampled_complexes/complex_names.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name allo-snp2
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/decoy_experiment/train_data_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/decoy_experiment/train_data --split_train /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/decoy_experiment/train_data/complex_names.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name allo-decoys
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/debug_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/debug --split_train /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/debug/complex_names.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name allo-debug
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/combo_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/combo --split_train combo_train_set.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name combo
#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/combo_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/combo --split_train combo_train_set2.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name combo2
python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/boost_esm/embeddings/ --pdbbind_dir /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/boost --split_train /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/kinase_md/boost/complex_names.txt --split_val allo_test_split.txt --val_inference_freq 10 --train_inference_freq 10 --n_epochs 100 --pin_memory --DDP --pretrain_dir='workdir/v1.1/score_model' --pretrain_ckpt='best_ema_inference_epoch_model' --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name allo-boost

