#!/bin/bash

source /ext3/env.sh
conda activate diffdock-pocket
cd /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/jeg10045_kinase_scripts/diffdock/DiffDock

# --pretrain_dir='workdir/v1.1/score_model/' --pretrain_ckpt='best_ema_inference_epoch_model'

#python train.py --config default_inference_args.yaml --restart_dir='workdir/test_score/super-2x-dropout-5e-1' --protein_file protein --cache_path /scratch/eac709/overlays/jeg/DiffDock-Confidence-Test/data/final_allo_only_splits_250612_supersample_x2 --pdbbind_esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/250612/data/250610_corrected_sdf_supersample/esm2/ --pdbbind_dir /vast/eac709/allo_crossdock/250610_corrected_sdf_supersample/ --split_train /scratch/projects/yzlab/group/kinase_eric/kinase_location_classifier/final_allo_only_splits_250604/train_supersample_x2.txt --split_val ../../../final_allo_only_splits_250604/val_x4.txt --val_inference_freq 100 --train_inference_freq 100 --n_epochs 7500 --num_dataloader_workers 4 --pin_memory --DDP --num_inference_complexes 50 --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name super-2x-dropout-5e-1 --dropout 0.5 --lr 0.0001 --inference_earlystop_avg_infsteps=10 --wandb_id 00u6w0uf

#python train.py --config default_inference_args.yaml --protein_file protein --restart_dir='workdir/test_score/weighted_tor_lin_final_splits' --pdbbind_esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --pdbbind_dir data/allosteric_dataset/ --split_train ../../../final_allo_only_splits_250604/train.txt --split_val ../../../final_allo_only_splits_250604/val_x4.txt --val_inference_freq 100 --train_inference_freq 100 --n_epochs 5000 --num_dataloader_workers 4 --pin_memory --DDP --num_inference_complexes 50 --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name weighted_tor_lin_final_splits --lr 0.0001 --weighted_tor 6 --inference_earlystop_avg_infsteps=10 --wandb_id oos9vihf

python train.py --config default_inference_args.yaml --pretrain_dir='workdir/v1.1/score_model/' --pretrain_ckpt='best_ema_inference_epoch_model' --protein_file protein --pdbbind_esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --pdbbind_dir data/allosteric_dataset/ --split_train ../../../final_allo_only_splits_250604/train.txt --split_val ../../../final_allo_only_splits_250604/val_x4.txt --val_inference_freq 100 --train_inference_freq 100 --n_epochs 15000 --num_dataloader_workers 4 --pin_memory --DDP --num_inference_complexes 100 --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name rng_0.5_4_4_2 --lr 0.0001 --rng_gamma 0.5 --rng_tr_eps 4.0 --rng_tor_eps 4.0 --rng_rot_eps 2.0 --inference_earlystop_avg_infsteps=10


#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --pdbbind_dir data/allosteric_dataset/ --split_train allo_train_split.txt --split_val allo_val_split.txt --restart_dir='workdir/test_score/weighted-tor3' --val_inference_freq 100 --train_inference_freq 100 --n_epochs 5000 --num_dataloader_workers 4 --pin_memory --DDP --num_inference_complexes 50 --wandb --entity jeg10045-new-york-university --project diffdock-tune --run_name weighted-tor3 --lr 0.0001 --weighted_tor 3 --wandb_id 6qcf4asm

#python train.py --config default_inference_args.yaml --protein_file protein --pdbbind_esm_embeddings_path /vast/eac709/allo_crossdock/DiffDock-L/AlloSet/241120/data/esm2/ --pdbbind_dir data/allosteric_dataset/ --split_train debug_train_split.txt --split_val debug_test_split.txt --val_inference_freq 100 --train_inference_freq 100 --n_epochs 10000 --num_dataloader_workers 4 --pin_memory --DDP --num_inference_complexes 50 --wandb --entity jeg10045-new-york-university --project hyperparam --run_name weighted_tor2 --lr 0.0001 --pretrain_dir='workdir/v1.1/score_model/' --pretrain_ckpt='best_ema_inference_epoch_model' --weighted_tor
